=== BLSQ/iaso/jsonschema/mobile-v4.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Schema for Sence HAT mobile data",
  "type": "object",
  "required": ["type", "dateCreated", "dateModified", "_id"],
  "properties": {
    "type": { "enum": ["participant"] },
    "dateCreated": { "type": "string", "format": "date-time" },
    "dateModified": { "type": "string", "format": "date-time" },
    "_id": { "type": "string", "format": "uuid" },
    "_rev": { "type": "string", "format": "uuid" },
    "person": { "$ref": "#/definitions/person" },
    "participant": { "$ref": "#/definitions/participant" }
  },
  "definitions": {
    "person": {
      "type": "object",
      "required": ["forename", "surname", "birthYear", "location"],
      "properties": {
        "forename": { "type": "string", "format": "name" },
        "surname": { "type": "string", "format": "name" },
        "postname": { "type": "string", "format": "name" },
        "gender": { "enum": ["Female", "Male"] },
        "birthYear": { "type": "integer", "minimum": 1900 },
        "mothersSurname": { "type": "string", "format": "name" },
        "location": { "$ref": "#/definitions/location" },
        "age": {
          "type": "object",
          "properties": {
            "years": { "type": "string", "format": "str-years" },
            "months": { "type": "string", "format": "str-months" }
          }
        }
      }
    },
    "participant": {
      "type": "object",
      "required": ["hatId", "screeningLocation"],
      "properties": {
        "version": { "type": "integer" },
        "hatId": { "type": "string" },
        "memberType": { "enum": ["traveller", "resident"] },
        "screeningLocation": { "$ref": "#/definitions/location" },
        "screenings": {
          "type": "object",
          "properties": {
            "rdt": { "$ref": "#/definitions/test" },
            "catt": { "$ref": "#/definitions/test" },
            "pg": { "$ref": "#/definitions/test" },
            "maect": { "$ref": "#/definitions/test" },
            "ctcwoo": { "$ref": "#/definitions/test" },
            "ge": { "$ref": "#/definitions/test" },
            "pl": { "$ref": "#/definitions/test" }
          }
        },
        "geoLocation": { "$ref": "#/definitions/geoLocation" }
      }
    },
    "test": {
      "type": "object",
      "properties": {
        "sessionType": { "enum": ["doorToDoor", "onTheSpot"] },
        "result": { "enum": ["negative", "positive"] },
        "group": { "type": "string", "format": "date-time" }
      }
    },
    "location": {
      "type": "object",
      "properties": {
        "zone": { "type": "string", "format": "location-zone" },
        "area": { "type": "string", "format": "location-area" },
        "village": { "type": "string", "format": "location-village" }
      }
    },
    "geoLocation": {
      "type": "object",
      "properties": {
        "latitude": { "type": "number" },
        "longitude": { "type": "number" }
      }
    }
  }
}

=== BLSQ/iaso/fixtures/backup-v4.json
[
  {
    "person": {
      "forename": "Kfhdhdjfj",
      "postname": "Vkhgjvhf",
      "surname": "Fjgfud",
      "age": {
        "years": "5"
      },
      "gender": "Female",
      "mothersSurname": "Mo",
      "location": {
        "zone": "mosango",
        "area": "mangungu",
        "village": "m-ngunguvilla"
      },
      "birthYear": 2011
    },
    "participant": {
      "memberType": "traveller",
      "screenings": {
        "rdt": {
          "sessionType": "doorToDoor",
          "result": "positive",
          "image": "file:///storage/emulated/0/Android/data/org.ehealthafrica.hat/files/e5fbe5ad-e11a-4f7d-be5e-430e0550bc95.jpg",
          "group": "2016-07-05T15:05:12.780Z"
        }
      },
      "screeningLocation": {
        "zone": "mosango",
        "area": "mangungu",
        "village": "m-ngunguvilla"
      },
      "hatId": "FJVKKFF2011M",
      "version": 4,
      "geoLocation": {
        "latitude": 0,
        "longitude": 0
      }
    },
    "type": "participant",
    "dateCreated": "2016-07-06T09:44:10.472Z",
    "dateModified": "2016-07-06T09:44:10.472Z",
    "_id": "participant-fjvkkff2011m",
    "_rev": "1-7d3634b7c3f50607f20fe94be4df36e6"
  },
  {
    "person": {
      "forename": "D4😡😢😴",
      "postname": "C3😉😯😐",
      "surname": "B3☺😮😑",
      "age": {
        "months": "11"
      },
      "gender": "Female",
      "mothersSurname": "Guga",
      "location": {
        "zone": "mosango",
        "area": "mangungu",
        "village": "m-ngunguvilla"
      },
      "birthYear": 2015
    },
    "participant": {
      "memberType": "resident",
      "screenings": {
        "rdt": {
          "sessionType": "doorToDoor",
          "result": "negative",
          "image": "file:///storage/emulated/0/Android/data/org.ehealthafrica.hat/files/9db0ac22-c787-4ada-b1a1-2a9dde1a6c8b.jpg",
          "group": "2016-07-06T09:44:17.680Z"
        }
      },
      "screeningLocation": {
        "zone": "mosango",
        "area": "mangungu",
        "village": "m-ngunguvilla"
      },
      "hatId": "B3C3D4F2015G",
      "version": 4,
      "geoLocation": {
        "latitude": 0,
        "longitude": 0
      }
    },
    "type": "participant",
    "dateCreated": "2016-07-06T09:45:44.761Z",
    "dateModified": "2016-07-06T09:45:44.761Z",
    "_id": "participant-b3c3d4f2015g",
    "_rev": "1-47008dcbde0bc26fe0be1ba145e8c2cb"
  },
  {
    "person": {
      "forename": "♤♡♢♧fk",
      "postname": "Ggaa🐏",
      "surname": "Huhba",
      "age": {
        "months": "11"
      },
      "gender": "Male",
      "mothersSurname": "Haba",
      "location": {
        "zone": "mosango",
        "area": "mangungu",
        "village": "m-ngunguvilla"
      },
      "birthYear": 2015
    },
    "participant": {
      "memberType": "traveller",
      "screenings": {
        "rdt": {
          "sessionType": "doorToDoor",
          "result": "positive",
          "image": "file:///storage/emulated/0/Android/data/org.ehealthafrica.hat/files/67271d01-97a1-4feb-8df4-11be9ffd24df.jpg",
          "group": "2016-07-06T09:44:17.680Z"
        }
      },
      "screeningLocation": {
        "zone": "mosango",
        "area": "mangungu",
        "village": "m-ngunguvilla"
      },
      "hatId": "HUGGFKM2015H",
      "version": 4,
      "geoLocation": {
        "latitude": 0,
        "longitude": 0
      }
    },
    "type": "participant",
    "dateCreated": "2016-07-06T09:46:54.006Z",
    "dateModified": "2016-07-06T09:46:54.006Z",
    "_id": "participant-huggfkm2015h",
    "_rev": "1-7eca4274b45977bec532fec52b06e579"
  },
  {
    "person": {
      "forename": "Bbøöőœõl",
      "postname": "Aa₩¥£€",
      "surname": "Dd《》☆⊙°•¿¡■□●○▪",
      "age": {
        "years": "22"
      },
      "gender": "Male",
      "mothersSurname": "Gg",
      "location": {
        "zone": "mosango",
        "area": "mangungu",
        "village": "m-ngunguvilla"
      },
      "birthYear": 1994
    },
    "participant": {
      "memberType": "resident",
      "screenings": {
        "rdt": {
          "sessionType": "doorToDoor",
          "result": "negative",
          "group": "2016-07-06T09:44:17.680Z"
        }
      },
      "screeningLocation": {
        "zone": "mosango",
        "area": "mangungu",
        "village": "m-ngunguvilla"
      },
      "hatId": "DDAABBM1994G",
      "version": 4,
      "geoLocation": {
        "latitude": 0,
        "longitude": 0
      }
    },
    "type": "participant",
    "dateCreated": "2016-07-06T09:48:12.879Z",
    "dateModified": "2016-07-06T09:48:12.879Z",
    "_id": "participant-ddaabbm1994g",
    "_rev": "1-f72e16849f8b42bebf4f9390d2a662fe"
  },
  {
    "person": {
      "forename": "VŲűůūüûúù",
      "postname": "HĖęěĕĕəèéêëē",
      "surname": "Ccåæāăąàáâãä",
      "age": {
        "years": "25"
      },
      "gender": "Female",
      "mothersSurname": "Gfd",
      "location": {
        "zone": "mosango",
        "area": "mangungu",
        "village": "m-ngunguvilla"
      },
      "birthYear": 1991
    },
    "participant": {
      "memberType": "resident",
      "screenings": {
        "rdt": {
          "sessionType": "doorToDoor",
          "result": "positive",
          "image": "file:///storage/emulated/0/Android/data/org.ehealthafrica.hat/files/06ab7c46-6d02-45d6-b55e-45762c40d8fc.jpg",
          "group": "2016-07-06T09:44:17.680Z"
        }
      },
      "screeningLocation": {
        "zone": "mosango",
        "area": "mangungu",
        "village": "m-ngunguvilla"
      },
      "hatId": "CCHEVUF1991G",
      "version": 4,
      "geoLocation": {
        "latitude": 0,
        "longitude": 0
      }
    },
    "type": "participant",
    "dateCreated": "2016-07-06T09:49:55.617Z",
    "dateModified": "2016-07-06T09:49:55.617Z",
    "_id": "participant-cchevuf1991g",
    "_rev": "1-e57e3281612a6aace34dd86b7235e63f"
  },
  {
    "person": {
      "forename": "Jojo",
      "postname": "Sojo",
      "surname": "Fghıįīïîíì",
      "age": {
        "years": "44"
      },
      "gender": "Male",
      "mothersSurname": "Hh",
      "location": {
        "zone": "mosango",
        "area": "kasay",
        "village": "camp-bulungu"
      },
      "birthYear": 1972
    },
    "participant": {
      "memberType": "resident",
      "screenings": {
        "catt": {
          "sessionType": "doorToDoor",
          "result": "positive",
          "level": "1",
          "image": "file:///storage/emulated/0/Android/data/org.ehealthafrica.hat/files/8bc63a16-c2b8-4a3b-9ef9-9f187541e60e.jpg",
          "screeningIndex": 1,
          "group": "2016-07-06T09:50:26.065Z"
        }
      },
      "screeningLocation": {
        "zone": "mosango",
        "area": "kasay",
        "village": "camp-bulungu"
      },
      "hatId": "FGSOJOM1972H",
      "version": 4,
      "geoLocation": {
        "latitude": 0,
        "longitude": 0
      }
    },
    "type": "participant",
    "dateCreated": "2016-07-06T09:51:28.197Z",
    "dateModified": "2016-07-06T09:51:28.197Z",
    "_id": "participant-fgsojom1972h",
    "_rev": "1-e426ac940d1cba1d23d8130d2e579a96"
  },
  {
    "person": {
      "forename": "Jggg",
      "postname": "Hfff",
      "surname": "Jhfff",
      "age": {
        "years": "55"
      },
      "gender": "Male",
      "mothersSurname": "Gjf",
      "location": {
        "zone": "mosango",
        "area": "kasay",
        "village": "camp-bulungu"
      },
      "birthYear": 1961
    },
    "participant": {
      "memberType": "traveller",
      "screenings": {
        "catt": {
          "sessionType": "doorToDoor",
          "result": "positive",
          "level": "2",
          "image": "file:///storage/emulated/0/Android/data/org.ehealthafrica.hat/files/20dfc5e3-725f-4db5-9032-6759b97bf69d.jpg",
          "screeningIndex": 2,
          "group": "2016-07-06T09:50:26.065Z"
        }
      },
      "screeningLocation": {
        "zone": "mosango",
        "area": "kasay",
        "village": "camp-bulungu"
      },
      "hatId": "JHHFJGM1961G",
      "version": 4,
      "geoLocation": {
        "latitude": 0,
        "longitude": 0
      }
    },
    "type": "participant",
    "dateCreated": "2016-07-06T09:52:02.096Z",
    "dateModified": "2016-07-06T09:52:02.096Z",
    "_id": "participant-jhhfjgm1961g",
    "_rev": "1-d9b8dbb4b36cc2394b09fff03f815953"
  },
  {
    "person": {
      "forename": "Cgy",
      "postname": "Ijn",
      "surname": "Fgdt",
      "age": {
        "years": "44"
      },
      "gender": "Male",
      "mothersSurname": "Dfg",
      "location": {
        "zone": "mosango",
        "area": "kasay",
        "village": "camp-bulungu"
      },
      "birthYear": 1972
    },
    "participant": {
      "memberType": "resident",
      "screenings": {
        "catt": {
          "sessionType": "doorToDoor",
          "result": "positive",
          "level": "0",
          "image": "file:///storage/emulated/0/Android/data/org.ehealthafrica.hat/files/064e6542-5b27-4844-9c0a-2185b246da1f.jpg",
          "screeningIndex": 3,
          "group": "2016-07-06T09:50:26.065Z"
        }
      },
      "screeningLocation": {
        "zone": "mosango",
        "area": "kasay",
        "village": "camp-bulungu"
      },
      "hatId": "FGIJCGM1972D",
      "version": 4,
      "geoLocation": {
        "latitude": 0,
        "longitude": 0
      }
    },
    "type": "participant",
    "dateCreated": "2016-07-06T09:52:56.502Z",
    "dateModified": "2016-07-06T09:52:56.502Z",
    "_id": "participant-fgijcgm1972d",
    "_rev": "1-dde6ca4ce4c63a5c441eb5a4c3ec7631"
  },
  {
    "person": {
      "forename": "Rdc",
      "postname": "Esx",
      "surname": "Dsa",
      "age": {
        "years": "33"
      },
      "gender": "Female",
      "mothersSurname": "Rew",
      "location": {
        "zone": "mosango",
        "area": "kasay",
        "village": "camp-bulungu"
      },
      "birthYear": 1983
    },
    "participant": {
      "memberType": "traveller",
      "screenings": {
